{
 "title": "Jaeger",
 "tags": [
  "jaeger",
  "prometheus"
 ],
 "time": { "from": "now-1m", "to": "now" },
 "templating": {
  "list": [
   { "name": "svc", "label": "serviceName", "query": "label_values(svc)" }
  ]
 },
 "panels": [
  {
   "title": "Jaeger Collector",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Spans Received/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jaeger_spans_received_total[1m]))"
    }
   ]
  },
  {
   "title": "Average in-queue latency (sec)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jaeger_in_queue_latency_sum / jaeger_in_queue_latency_count"
    }
   ]
  },
  {
   "title": "Batch Size (spans)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jaeger_batch_size" }
   ]
  },
  {
   "title": "Queue Length (Spans)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jaeger_queue_length" }
   ]
  },
  {
   "title": "Spans Dropped/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(jaeger_spans_dropped_total[5m])"
    }
   ]
  },
  {
   "title": "Span save latency (sec)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jaeger_save_latency_sum / jaeger_save_latency_count"
    }
   ]
  },
  {
   "title": "trace_receive_total",
   "type": "graph",
   "description": "Trace接收总数",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jaeger_traces_received_total{svc=\"$svc\"}"
    }
   ]
  },
  {
   "title": "traces_saved_by_svc_total",
   "type": "graph",
   "description": "保存Save总数",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jaeger_traces_saved_by_svc_total{svc=\"$svc\"}"
    }
   ]
  },
  {
   "title": "span_received_total",
   "type": "graph",
   "description": "接收Span总数",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jaeger_spans_received_total{svc=\"$svc\"}"
    }
   ]
  },
  {
   "title": "spans_saved_by_svc_total",
   "type": "graph",
   "description": "保存Span总数",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jaeger_spans_saved_by_svc_total{svc=\"$svc\"}"
    }
   ]
  },
  {
   "title": "Jaeger Agent",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {}
   ]
  },
  {
   "title": "jaeger_agent_thrift_udp_server_packets_processed/sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jaeger_thrift_udp_server_packets_processed_total[5m])) by (protocol)"
    }
   ]
  },
  {
   "title": "avg(jaeger_agent_thrift_udp_server_packet_size)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(jaeger_thrift_udp_server_packet_size) by (protocol)"
    }
   ]
  },
  {
   "title": "jaeger_agent_thrift_udp_server_queue_size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(jaeger_thrift_udp_server_queue_size) by (protocol)"
    }
   ]
  },
  {
   "title": "jaeger_agent_thrift_udp_server_read_errors/sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jaeger_thrift_udp_server_read_errors_total[5m])) by (protocol)"
    }
   ]
  },
  {
   "title": "jaeger_agent_thrift_udp_server_packets_dropped/sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jaeger_thrift_udp_server_packets_dropped_total[5m])) by (protocol)"
    }
   ]
  },
  {
   "title": "jaeger_agent_thrift_udp_t_processor_handler_errors/sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jaeger_thrift_udp_t_processor_handler_errors_total[5m])) by (protocol)"
    }
   ]
  },
  {
   "title": "jaeger_agent_tchannel_reporter_batches_submitted/sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jaeger_agent_reporter_batches_submitted_total[5m])) by (format)"
    }
   ]
  },
  {
   "title": "jaeger_agent_tchannel_reporter_spans_submitted/sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jaeger_agent_reporter_spans_submitted_total[5m])) by (format)"
    }
   ]
  },
  {
   "title": "avg(jaeger_agent_tchannel_reporter_batch_size)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(jaeger_agent_reporter_batch_size) by (format)"
    }
   ]
  },
  {
   "title": "jaeger_agent_http_server_requests/sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jaeger_http_server_requests_total[5m])) by (type)"
    }
   ]
  },
  {
   "title": "jaeger_agent_tchannel_reporter_batches_failures/sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jaeger_agent_reporter_batches_failures_total[5m])) by (format)"
    }
   ]
  },
  {
   "title": "jaeger_agent_tchannel_reporter_spans_failures/sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jaeger_agent_reporter_spans_failures_total[5m])) by (format)"
    }
   ]
  },
  {
   "title": "jaeger_agent_http_server_errors/sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jaeger_http_server_errors_total[5m])) by (source, status)",
     "legendFormat": "{{source}}.{{status}}"
    }
   ]
  },
  {
   "title": "total(jaeger_agent_collector_proxy)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jaeger_agent_collector_proxy_total) by (endpoint,protocol,result)"
    }
   ]
  },
  {
   "title": "Jaeger Query",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Average request latency (milliseconds)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(jaeger_rpc_request_latency_sum / jaeger_rpc_request_latency_count)*1000"
    }
   ]
  },
  {
   "title": "Requests/min (All requests)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jaeger_rpc_http_requests_total[5m]))*60",
     "legendFormat": "All requests (/min)"
    },
    {
     "expr": "sum(rate(jaeger_rpc_http_requests_total{status_code=~\"2xx\"}[5m]))*60",
     "legendFormat": "2xx Requests (/min)"
    },
    {
     "expr": "sum(rate(jaeger_rpc_http_requests_total{status_code!=\"2xx\"}[5m]))*60",
     "legendFormat": "Non-2xx Requests (/min)"
    }
   ]
  },
  {
   "title": "Requests/min (endpoint=\"/api/traces\")",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jaeger_rpc_http_requests_total{endpoint=~\"/api/traces\"}[5m]))*60",
     "legendFormat": "All requests (/min)"
    },
    {
     "expr": "sum(rate(jaeger_rpc_http_requests_total{endpoint=~\"/api/traces\",status_code=~\"2xx\"}[5m]))*60",
     "legendFormat": "2xx Requests (/min)"
    },
    {
     "expr": "sum(rate(jaeger_rpc_http_requests_total{endpoint=~\"/api/traces\",status_code!=\"2xx\"}[5m]))*60",
     "legendFormat": "Non-2xx Requests (/min)"
    }
   ]
  },
  {
   "title": "Requests/min (endpoint=\"/api/traces/-traceID-\")",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jaeger_rpc_http_requests_total{endpoint=~\"/api/traces/-traceID-\"}[5m]))*60",
     "legendFormat": "All requests (/min)"
    },
    {
     "expr": "sum(rate(jaeger_rpc_http_requests_total{endpoint=~\"/api/traces/-traceID-\",status_code=~\"2xx\"}[5m]))*60",
     "legendFormat": "2xx Requests (/min)"
    },
    {
     "expr": "sum(rate(jaeger_rpc_http_requests_total{endpoint=~\"/api/traces/-traceID-\",status_code!=\"2xx\"}[5m]))*60",
     "legendFormat": "Non-2xx Requests (/min)"
    }
   ]
  },
  {
   "title": "Requests/min (endpoint=\"/api/services/-service-/operations\")",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jaeger_rpc_http_requests_total{endpoint=~\"/api/services/-service-/operations\"}[5m]))*60",
     "legendFormat": "All requests (/min)"
    },
    {
     "expr": "sum(rate(jaeger_rpc_http_requests_total{endpoint=~\"/api/services/-service-/operations\",status_code=~\"2xx\"}[5m]))*60",
     "legendFormat": "2xx Requests (/min)"
    },
    {
     "expr": "sum(rate(jaeger_rpc_http_requests_total{endpoint=~\"/api/services/-service-/operations\",status_code!=\"2xx\"}[5m]))*60",
     "legendFormat": "Non-2xx Requests (/min)"
    }
   ]
  },
  {
   "title": "Requests/min (endpoint=\"/api/services\")",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jaeger_rpc_http_requests_total{endpoint=~\"/api/services\"}[5m]))*60",
     "legendFormat": "All requests (/min)"
    },
    {
     "expr": "sum(rate(jaeger_rpc_http_requests_total{endpoint=~\"/api/services\",status_code=~\"2xx\"}[5m]))*60",
     "legendFormat": "2xx Requests (/min)"
    },
    {
     "expr": "sum(rate(jaeger_rpc_http_requests_total{endpoint=~\"/api/services\",status_code!=\"2xx\"}[5m]))*60",
     "legendFormat": "Non-2xx Requests (/min)"
    }
   ]
  }
 ]
}